# Linear Regressor

Code used to estimate the regression coefficients using Least Squares and Neural Networks.

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

2023-11-07 20:27:44.789666: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-07 20:27:44.880831: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-07 20:27:45.292349: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-07 20:27:45.292390: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-07 20:27:45.294354: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to regi

In [3]:
# Generate random data for regression
X = np.random.multivariate_normal(np.zeros(5),np.eye(5),1000)
X = np.concatenate((X, np.ones((1000,1))), axis = 1)

# B matrix with coefficients
B = np.random.uniform(-10,10,6)

# Dependent variable Y with random noise
Y = X@B + np.random.uniform(0, 1, 1000)

In [4]:
input_size = 6
output_size = 1
model = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size)
])

In [ ]:
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
model.compile(optimizer=custom_optimizer, loss = 'mean_squared_error')
model.fit(X, Y, epochs = 100, verbose = 1)

In [178]:
# Compute loss
def squared_loss(Y, Y_hat):
    return sum((model(X) - Y.reshape((1000,1)))**2)

In [191]:
# Define the model
inputs = tf.keras.Input(shape=(6,))
outputs =  tf.keras.layers.Dense(1, use_bias = False)(inputs)
model = tf.keras.Model(inputs = inputs, outputs = outputs)

learning_rate = 0.0001
for i in np.arange(1,1000):

    with tf.GradientTape() as tape:
        loss = squared_loss(Y, model(X))

    grad = tape.gradient(loss, model.trainable_variables)
    model.layers[1].set_weights(model.layers[1].get_weights() - grad[0]*learning_rate)
    print(loss)
    if loss < 0.01:
        break

tf.Tensor([260855.25], shape=(1,), dtype=float32)
tf.Tensor([162353.89], shape=(1,), dtype=float32)
tf.Tensor([101468.875], shape=(1,), dtype=float32)
tf.Tensor([63695.848], shape=(1,), dtype=float32)
tf.Tensor([40170.176], shape=(1,), dtype=float32)
tf.Tensor([25458.273], shape=(1,), dtype=float32)
tf.Tensor([16219.081], shape=(1,), dtype=float32)
tf.Tensor([10391.349], shape=(1,), dtype=float32)
tf.Tensor([6698.9116], shape=(1,), dtype=float32)
tf.Tensor([4348.657], shape=(1,), dtype=float32)
tf.Tensor([2845.7854], shape=(1,), dtype=float32)
tf.Tensor([1880.2998], shape=(1,), dtype=float32)
tf.Tensor([1257.1716], shape=(1,), dtype=float32)
tf.Tensor([853.158], shape=(1,), dtype=float32)
tf.Tensor([590.03406], shape=(1,), dtype=float32)
tf.Tensor([417.91684], shape=(1,), dtype=float32)
tf.Tensor([304.85327], shape=(1,), dtype=float32)
tf.Tensor([230.27852], shape=(1,), dtype=float32)
tf.Tensor([180.89943], shape=(1,), dtype=float32)
tf.Tensor([148.08302], shape=(1,), dtype=float32)
tf

KeyboardInterrupt: 